fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort . --profile black
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: poetry run flake8 .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Bandit
        entry: poetry run bandit --exclude /tests -r .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Safety
        entry: poetry run safety check
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Tests
        entry: poetry run pytest --cov .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Coverage
        entry: poetry run coverage report # --fail-under=90
        pass_filenames: false
        language: system
  # - repo: local
  #   hooks:
  #     - id: system
  #       name: Documentation
  #       entry: ./pyreverse.sh
  #       pass_filenames: false
  #       language: system