name: Continuous Integration and Delivery

on: [push]

jobs:

  admin:
    name: Build Up Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Quality Check
        run: make quality-check
      - name: Security
        run: make secure